class MarketYandexLocators:

    LOGIN = '//*[@id="USER_MENU_ANCHOR"]/div'
    LOGO = '//*[@id="MainHeader"]/div/header/div[1]/div/noindex/div/div/a[2]'
    SEARCH = '//*[@id="header-search"]'
    FORM_LOGIN = '//*[@id="root"]/div/div[2]/div[2]/div/div/div[1]'
    INPUT_SEARCH = '//*[@id="header-search"]'
    BUTTON_SEARCH = '//*[@id="MainHeader"]/div/header/div[1]/div/div/div/div/div/div/form/div/button'
    RESULT1 = '//*[@id="pcxwhp33rn"]/div/div/div[2]/div[1]/div/a'
    PAGE_SEARCH = '//*[@id="/content/page/fancyPage/cms"]/div'
    BUTTON_CATALOG = '//*[@id="MainHeader"]/div/header/div[1]/div/div/noindex[1]/div/div'
    CATALOG = '/html/body/div[7]'
    BUTTON_LOGIN = '//*[@id="USER_MENU_ANCHOR"]/div/div/a'
    NAME = '//*[@id="passp-field-login"]'
    SING_IN ='//*[@id="passp:sign-in"]'
    NAME_ENTERED = '//*[@id="root"]/div/div[2]/div[2]/div/div/div[2]/div[3]/div/div/form/div/div[2]/div[1]/a/span[2]/span'
    BASKET = '//*[@id="MainHeader"]/div/header/div[1]/div/div/noindex[2]/nav/ul/li[4]/div/div'
    BASKET_PAGE = '//*[@id="cartItems"]/div[2]/div/div[2]/div[1]/div/div/div/ul/li/div/div'
    START_PAGE = '//*[@id="MainHeader"]/div/header/div[1]/div/noindex/div/div/a[2]'
    ORDERS = '//*[@id="MainHeader"]/div/header/div[1]/div/div/noindex[2]/nav/ul/li[3]/div'
    ORDERS_PAGE = '//*[@id="/content/page/fancyPage/layout/searchList/emptyState"]/div'
    FAVORITES = '//*[@id="MainHeader"]/div/header/div[1]/div/div/noindex[2]/nav/ul/li[3]/div'
    FAVORITES_PAGE = '//*[@id="/content/page/fancyPage/layout/searchList/emptyState"]/div/div'